### ISSUE TITLE
Custom mappings

### ISSUE THREAD

**Issue by sparkcanon** [prabirshrestha/quickpick.vim#14]
Hi Prabir, Would you able to share an example on how to add custom mappings such as `Ctrl-v` to open a file in a vertical split?

**Comment by prabirshrestha** [comment]
Currently it is not supported. I still need to figure out what the best way is to expose it. It is something I want to do but still thinking.

I need to make sure I get the apis right which is currently the blocker and not the implementation.

**Comment by sparkcanon** [comment]
Fair enough, thanks for taking the time to reply. It is indeed a good idea to get the APIs right first.
