### ISSUE TITLE
How does a user actually use quickpick?

### ISSUE THREAD

**Issue by Hyperlynx2** [prabirshrestha/quickpick.vim#37]
I'm trying to use `:LspWorkspaceSymbolSearch`, which the docs say is powered by this plugin. But how do I actually select an option in it? If I hit enter it jumps to the first selection in the list. I can't use ctrl+w to get to the list to select another option.

How does it work? :/

**Comment by prabirshrestha** [comment]
Usually you don't installing this plugin at all unless you are someone writing the plugin. As for your case, you can use [vim-lsp](https://github.com/prabirshrestha/vim-lsp) which bundles quickpick.vim. You can then use [:LspWorkspaceSymbolSearch](https://github.com/prabirshrestha/vim-lsp/blob/d36f381dc8f39a9b86d66ef84c2ebbb7516d91d6/doc/vim-lsp.txt#L1909-L1912) or [: LspDocumentSymbolSearch](https://github.com/prabirshrestha/vim-lsp/blob/d36f381dc8f39a9b86d66ef84c2ebbb7516d91d6/doc/vim-lsp.txt#L1787-L1789)

**Comment by Hyperlynx2** [comment]
Yes, and as I asked above: 
> how do I actually select an option in it? If I hit enter it jumps to the first selection in the list. I can't use ctrl+w to get to the list to select another option.

**Comment by prabirshrestha** [comment]
Mapping should be here. https://github.com/prabirshrestha/quickpick.vim/blob/0d5357ec3b8fd5c8c99beb2285435b7d8d1a40cc/autoload/quickpick.vim#L96-L120

If you don't like the defaults, you can override it to your custom mapping.
